# Generated by Django 6.0.5 on 2026-05-27 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mandante', models.CharField(max_length=50, verbose_name='Mandante')),
                ('time_visitante', models.CharField(max_length=50, verbose_name='Visitante')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do Jogo')),
                ('gols_mandante', models.IntegerField(blank=True, null=True, verbose_name='Gols Mandante')),
                ('gols_visitante', models.IntegerField(blank=True, null=True, verbose_name='Gols Visitante')),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_mandante', models.IntegerField(verbose_name='Palpite Gols Mandante')),
                ('gols_visitante', models.IntegerField(verbose_name='Palpite Gols Visitante')),
                ('pontos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
        ),
    ]
