# Generated by Django 6.0.5 on 2026-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='multiplicador',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='gols_mandante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='gols_visitante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols_mandante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time_mandante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time_visitante',
            field=models.CharField(max_length=50),
        ),
    ]
