# Generated by Django 6.0.5 on 2026-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partida_multiplicador_alter_palpite_gols_mandante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='bandeira_mandante',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='bandeira_visitante',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='grupo_fase',
            field=models.CharField(default='Fase de Grupos', max_length=50),
        ),
    ]
